### ISSUE TITLE
From another w3c implementation: hello!

### ISSUE THREAD

**Issue by mercmobily** [w3c-webdriver/w3c-webdriver#27]
Hi there,

I  have just finished developing [best-webdriver](https://github.com/mercmobily/best-webdriver). I also wrote [full documentation](https://mercmobily.github.io/best-webdriver/index.html) for it.

 I am aware of your module since, before developing bets-webdriver, I considered yours as one possibility, but then decided to create something from scratch. I did it by carving out minutes here and there, and working on it late at night after work, in just under 12 days (!). I started from scratch, not knowing the specs at all; I am in the process of writing tests as we speak.

Questions:

* Since I am the new kid in the block, and have only seen the specs less than 2 weeks ago, it would mean the world to me if you could have a look at what I wrote. Did I do anything terribly stupid?

* If you think my project happens to be ahead (I assume you are strapped with time, like all of us here...), feel free to use it. However, note that IE and Safari aren't tested yet (I don't have a Mac or a Windows machine)

* If you happen to want to join forces, I am all ears. I realise that I should have said this 12 days ago, rather than today -- sorry about that.

In general, I would love to know how your adventure into the specs is going, and when you will complete this API!

**Comment by mucsi96** [comment]
Hi there!

Thanks for writing. Really appreciate that! 👍 

Sorry for my English. It's not native for me :)

Your project looks amazing!. My favorite part is
"The API is async/await friendly. Each call returns a promise. Development is a breeze
Easy to debug. There is a 1:1 mapping between calls and the webdriver protocol, without trickery"
and
"Down to metal webdriver; you will be testing in 20 minutes, not 20 hours"

That's absolutely what I wanted to archive with my package and what I miss from `selenium-webdriver`, `webdriverio` or `nightwatch`. I wanted to create a package which has one-to-one mapping to REST API of WebDriver. And later maybe create some helper utility package for more convenient usage. What I wanted to specially avoid is adding some stupid runner. We have so much test runners :)

The name of my package can be  misleading. Currently I am not representing W3C. This was the best name I could come up in NPM namespace. But It was one of my plans after I cover the API to propose moving the repository under W3C GitHub namespace. 

I would love to join the forces. I suggest to continue the talk on https://gitter.im/mucsi96/w3c-webdriver
Cheers!

**Comment by mercmobily** [comment]
Hi Igor,

Your English sounds (or well... reads) perfect!
Thank you for your kind words. I wasn't quite sure what your reaction would be... I was a little nervous. But, by looking at both projects, it really looks like we had very similar ideas in mind. In fact, proposing my project to the W3C was _also_ my idea!

Please let me apologise again for creating something from scratch... I loved the ideas about your projects (we established they are very similar), but I saw that it was really still only 119 SLOC, it used a testing suite I wasn't used to, and finally... I wasn't sure how I wanted to approach it all. 

There are many ways we could join forces. I think the part where best-webdriver really shines is waitFor(), for example: it's like a super-easy way of creating a polling API without creating over-complicated selector functions.

I also think the way browsers are implemented -- as well as the `exec` function -- is something you could take in (I would be happy helping out adding those).

Or, we could just merge the two and work on the codebase together. I don't have access to Windows or Mac, for example. Just let me know -- I am happy to help and facilitate this in any way.

Merc.

**Comment by mercmobily** [comment]
In the meantime, I gave in and ended up having specific drivers (ChromeDriver, FirefoxDriver, etc.) which include some "shims" to make things work when they are broken at implementation level... ugh.

**Comment by mucsi96** [comment]
Hi Tony! Thanks again for writing! I just wanted to let you know that this package achieved 100% feature coverage of the spec and it reached a stable state. Test coverage improved to 100% and docs now are in quite good shape I would say. Sure we will do further improvements on docs by adding more examples and some tutorials. I would be more that happy if you can use it anyhow in future, provide some feedback or contribute to it 😊 Closing this issue for now. 😉

**Comment by mercmobily** [comment]
I haven't worked on this for a while now, basically waiting for Chrome to actually implement the specs.
Their [Chrome status page](https://chromium.googlesource.com/chromium/src.git/+/master/docs/chromedriver_status.md) looked like a total war zone last year. Now, it's looking a LOT happier. So, having a W3 webdriver might actually make sense.

I just could see myself becoming as bloated and difficult as Selenium, using non-standard protocols...

I will get back to this later this year. Thanks.
