### ISSUE TITLE
Get rid of required request and use native one

### ISSUE THREAD

**Issue by GaborSzalay** [w3c-webdriver/w3c-webdriver#6]
Get rid of required request and use native one

**Comment by GaborSzalay** [comment]
I don't remember the reason of this issue. @mucsi96 would you like to get this implemented here? Is this issue still relevant for you?

**Comment by mucsi96** [comment]
Hi,

Yes I am waiting for @netgrafe to implement this. Hope he will have time for this. :smile:

**Comment by mucsi96** [comment]
Fixed in release `0.0.7`
