### ISSUE TITLE
👋 from another WebDriver implementation

### ISSUE THREAD

**Issue by christian-bromann** [w3c-webdriver/w3c-webdriver#73]
I just stumbled upon this and was curious what the goal of this package is gonna be. I build a similar package with a similar interface called [`webdriver`](https://www.npmjs.com/package/webdriver) which already provides all commands, including a fallback for the JSONWireProtocol as well as all Appium commands and other things like Chromium and SauceLabs commands. I was curious if you guys are missing something in the current `webdriver` package or if you guys try to achieve a different goal with this one.

If we find a common ground we might save ourself a lot of time 😉 The `webdriver` is a core package of the WebdriverIO project which is part of the [OpenJS Foundation](https://medium.com/@nodejs/introducing-the-openjs-foundation-the-next-phase-of-javascript-ecosystem-growth-d4911b42664f).

**Comment by mucsi96** [comment]
Hi Christian! Thanks for writing! I appreciate you huge contribution to open source. I love that you decided to extract the core webdriver functionality to separate package. I far as I remember when I started this project there was no separation yet. The goal with this project is to have a minimal webdriver implementation of W3C protocol. I wanted to create a package which provides one to one mapping to the REST API. I decided to make it in TypeScript to support more users and provide better development experience with autocompletion and inline documentation. Also I wanted to cover everything with integration tests to make sure that the users will have no problems using it. If some browser is not supporting some use case would be create to document it. Also I wanted to create a rich documentation for every endpoint with examples. After covering the whole API and making sure it's stable I wanted to try to move it under W3C or Selenium organization and make it part of web platform tests where they currently use a python based client. Would be great if we can join the efforts.

**Comment by christian-bromann** [comment]
These are all great goals, let me give you some context on what the `webdriver` package currently supports:

> have a minimal webdriver implementation of W3C protocol

This is exactly what I've tried to. In the earlier versions of WebdriverIO I have written command files for each protocol command (e.g. [`getElementIdRect`](https://github.com/webdriverio-boneyard/v4/blob/master/lib/protocol/elementIdRect.js)), this created a huge maintenance effort. With the `webdriver` package all protocol commands are defined with [json](https://github.com/webdriverio/webdriverio/tree/master/packages/webdriver/protocol) files and every command call is generalized (property type checks, request, logging etc).

> I decided to make it in TypeScript to support more users and provide better development experience with autocompletion and inline documentation.

This is also supported in also auto generated based on the protocol json files.

> Also I wanted to cover everything with integration tests to make sure that the users will have no problems using it.

With WebdriverIO v4 I also had integration tests running most of the commands against a real browser on e.g. SauceLabs. This turned out to be a bad idea because tests became flakey and slow. Therefor I stopped doing this in v5 of WebdriverIO and only applied unit tests. Due to the fact that browser driver are tested in WPT I think there is no real value running the commands against actual drivers.

> If some browser is not supporting some use case would be create to document it.

This data should be available in the [WPT results](https://wpt.fyi/results/webdriver/tests?label=master&product=chrome%5Bexperimental%5D&product=edge&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&aligned). Note that every command can work differently in certain edge cases and covering this within a client project seems unnecessary imo.

> Also I wanted to create a rich documentation for every endpoint with examples.

This is also autogenerated by the json files: https://webdriver.io/docs/api/webdriver.html

> After covering the whole API and making sure it's stable I wanted to try to move it under W3C or Selenium organization and make it part of web platform tests where they currently use a python based client.

Did you talk to people from WPT about that? I am not sure if there is a plan to move all current webdriver tests to JS since all of them are currently written in Python like a ton of other WPT tests.

**Comment by mucsi96** [comment]
Hi Christian! Thanks again for writing! I just wanted to let you know that this package achieved 100% feature coverage of the spec and it's reached a stable state. Test coverage improved to 100% and docs now are in quite good shape I would say. Sure we will do further improvements on docs by adding more examples and some tutorials. I would be more that happy if you can use it anyhow in future, provide some feedback or contribute to it 😊 Closing this issue for now. 😉
